/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2022 MediaTek Inc.
 */

#include <linux/arm-smccc.h>
#include <linux/soc/mediatek/mtk_sip_svc.h>


enum conn_smc_opid {
	/* gps_hw_ops */
	SMC_GPS_WAKEUP_CONNINFRA_TOP_OFF_OPID = 1,
	SMC_GPS_COMMON_ON_PART1_OPID,
	SMC_GPS_COMMON_ON_PART2_OPID,
	SMC_GPS_COMMON_ON_PART3_OPID,
	SMC_GPS_COMMON_ON_PART4_OPID,
#if GPS_DL_CONNAC3
	SMC_GPS_COMMON_ON_CONTROL_ADIE_ON_1_OPID,
	SMC_GPS_COMMON_ON_CONTROL_ADIE_ON_2_OPID,
#endif
	SMC_GPS_COMMON_ON_FAIL_HANDLER_OPID,
	SMC_GPS_COMMON_ON_INNER_FAIL_HANDLER_OPID,
	SMC_GPS_COMMON_ON_PART5_OPID,
	SMC_GPS_DL_HW_GPS_PWR_STAT_CTRL_OPID,
	SMC_GPS_DL_SET_DSP_ON_AND_POLL_ACK_OPID,
	SMC_GPS_DL_HW_USRT_CTRL_OPID,
	SMC_GPS_DL_SET_CFG_DSP_MEM_AND_DSP_OFF_OPID,
	SMC_GPS_COMMON_OFF_PART1_OPID,
	SMC_GPS_COMMON_OFF_PART2_OPID,
	SMC_GPS_SW_REQUEST_EMI_USAGE_OPID,
	SMC_GPS_COMMON_OFF_PART3_OPID,

	/* gps_hw_irq */
	SMC_GPS_DL_HW_GET_MCUB_INFO_OPID,
	SMC_GPS_DL_HW_CLEAR_MCUB_D2A_FLAG_OPID,
	SMC_GPS_DL_HW_POLL_USRT_DSP_RX_EMPTY_OPID,
	SMC_GPS_DL_HW_SET_DMA_START_OPID,
	SMC_GPS_DL_HW_GET_MCUB_A2D_FLAG_OPID,
	SMC_GPS_DL_HW_MCUB_DSP_READ_REQUEST_OPID,
	SMC_GPS_DL_HW_USRT_HAS_SET_NODATA_FLAG_OPID,
	SMC_GPS_DL_HW_USRT_CLEAR_NODATA_IRQ_OPID,
	SMC_GPS_DL_HW_GET_DMA_LEFT_LEN_OPID,
	SMC_GPS_DL_HW_SET_DMA_STOP_OPID,
	SMC_GPS_DL_HW_USRT_IRQ_ENABLE_OPID,
	SMC_GPS_DL_HW_GET_DMA_INT_STATUS_OPID,
	SMC_GPS_MVCD_GET_DSP_BOOT_UP_INFO,
	SMC_GPS_MVCD_SEND_DSP_FRAGEMENT,
};

enum gps_dl_hw_mvcd_dsp_type {
	GPS_DL_MVCD_DSP_L1 = 0,
	GPS_DL_MVCD_DSP_L5,
	GPS_DL_MVCD_DSP_L1_CW,
	GPS_DL_MVCD_DSP_L5_CW,
	GPS_DL_MVCD_DSP_RESERVED1,
	GPS_DL_MVCD_DSP_RESERVED2,
};

bool gps_dl_hw_gps_force_wakeup_conninfra_top_off(bool enable);

